export enum InterviewTopic {
  JAVA = 'JAVA',
  SPRING_BOOT = 'SPRING_BOOT',
  ANGULAR = 'ANGULAR',
  SQL = 'SQL',
  REST_API = 'REST_API',
  DOCKER = 'DOCKER',
  KUBERNETES = 'KUBERNETES',
  GENERAL_SOFTWARE_ENGINEERING = 'GENERAL_SOFTWARE_ENGINEERING',
  BEHAVIORAL = 'BEHAVIORAL'
}